### ISSUE TITLE
Animu detecting shows with "TV" or "Special/s" as same show & several other issues

### ISSUE THREAD

**Issue by wopian** [hypereddie/Animu#21]
The information about the conflict(s) is also completely useless when the show(s) are detected as "TV" and with no reference to the file name/path it's matching against.

![](http://a.pomf.se/viakqk.png)
![](http://a.pomf.se/sqqinh.png)

---
---
---

When initially scanning folder, the "Found x anime(s)" constantly resets to 0.
[Video demo](http://a.pomf.se/mlqxkp.mp4). Possibly related to other issues i'm getting.

---
---
---
Animu recognises the files, but only detects their episode number. Resulting in endless cards with no title, thumbnail etc. [Video demo](http://a.pomf.se/zkxzrr.mp4)

**Comment by hypereddie** [comment]
In commit 08a8bdb, [more keywords were added](https://github.com/hypereddie/Animu/commit/08a8bdb8a574d4cf0cd024a1285b21e8967d7803#diff-49c629e33caa056d4bcc5b1e9e3804e0R627) to prevent this kind of issue.
