### ISSUE TITLE
[Feature Request] Allow choosing multiple folders to detect anime in.

### ISSUE THREAD

**Issue by Wopian** [hypereddie/Animu#22]
Currently, only 1 folder can be chosen to detect anime in. For most people this is perfectly fine. However, in cases like mine where I split films, TV and OVAs into separate folders. I can't just use the parent folder of these folders as I also have live action & western content in the parent folder.

```plain
Television
    Anime`Film
    Anime`OVA
    Anime`TV
    Cartoon`Film
    Cartoon`TV
    Film
    Tokusatsu`TV
    Tokusatsu`Film
    TV
```

**Comment by hypereddie** [comment]
Is something like this what your looking for?

![screenshot1](http://puu.sh/ffiJV/b62374fb3b.png)

![screenshot2](http://puu.sh/ffibd/e601e8e0be.png)

**Comment by Wopian** [comment]
:+1:
